apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
        - name: inventoryservice
          image: dgiap/fashion-inventory-service:latest
          resources:
            requests:
              memory: "32Mi"    # Giảm xuống 64MB RAM tối thiểu
              cpu: "50m"        # Giảm xuống 0.05 core CPU
            limits:
              memory: "256Mi"   # Giới hạn ở 128MB RAM
              cpu: "200m"       # Giới hạn ở 0.1 core CPU
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: inventoryservice
  ports:
  - name:  inventoryservice
    protocol: TCP
    port : 8080
    targetPort: 8080
  - name: inventoryservice-grpc
    protocol: TCP
    port : 666
    targetPort: 666