apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: dgiap/fashion-order-service:latest
          resources:
            requests:
              memory: "32Mi"    # Giảm xuống 64MB RAM tối thiểu
              cpu: "50m"        # Giảm xuống 0.05 core CPU
            limits:
              memory: "128Mi"   # Giới hạn ở 128MB RAM
              cpu: "200m"       # Giới hạn ở 0.1 core CPU
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: orderservice
  ports:
  - name: orderservice
    protocol: TCP
    port : 8080
    targetPort: 8080
  - name: orderservice-grpc
    protocol: TCP
    port : 666
    targetPort: 666