apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: dgiap/fashion-product-service:latest
          resources:
            requests:
              memory: "32Mi"    # Giảm xuống 64MB RAM tối thiểu
              cpu: "50m"        # Giảm xuống 0.05 core CPU
            limits:
              memory: "256Mi"   # Giới hạn ở 128MB RAM
              cpu: "200m"       # Giới hạn ở 0.1 core CPU
---
apiVersion: v1
kind: Service
metadata:
  name: productservice-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: productservice
  ports:
  - name: productservice
    protocol: TCP
    port : 8080
    targetPort: 8080
  - name: productservice-grpc
    protocol: TCP
    port : 666
    targetPort: 666