apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: dgiap/fashion-user-service:latest
          resources:
            requests:
              memory: "32Mi"    # Giảm xuống 64MB RAM tối thiểu
              cpu: "5m"        # Giảm xuống 0.05 core CPU
            limits:
              memory: "256Mi"   # Giới hạn ở 128MB RAM
              cpu: "200m"       # Giới hạn ở 0.1 core CPU
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: userservice
    protocol: TCP
    port : 8080
    targetPort: 8080
  - name: userservice-grpc
    protocol: TCP
    port : 666
    targetPort: 666
---
apiVersion: v1
kind: Service
metadata:
  name: user-loadbalancer-srv
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: userservice
---
# filepath: e:\DoAnTotNghiep\project\fashion_shop\FashionShop\k8s\user-depl.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-nodeport-srv
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30021 # You can specify a port between 30000-32767
  selector:
    app: userservice